# jira_backlog.py — Backlog complet projet nutrition-manager (backend)
# Dernière mise à jour : 2026-05-02
# Source de vérité : docs/backend/livrable/jira-backlog-decomposition.md
# Moteur d'import   : python3 playbook/tools/import_jira.py docs/backend/livrable/jira_backlog.py
#
# FORMAT DES TUPLES :
#   EPICS    : (ref, summary, description, label)
#   STORIES  : (ref, summary, description, priority, label, story_points, epic_ref)
#   SUBTASKS : (ref, summary, description, priority, label, story_ref)
#
# PLAGE DE REFS BACKEND : EPIC-001→099 | STORY-001→099 | SUB-001→299

MODULE = "backend"
MODE   = "create"

# ── Epics ──────────────────────────────────────────────────────────────────────

EPICS = [
    ("EPIC-001", "Domain Layer",         "Entités métier, value objects, enums et invariants. Zéro dépendance externe.", "domain"),
    ("EPIC-002", "Application Layer",    "Services applicatifs et DTOs. Orchestre les use cases depuis le domaine.",     "application"),
    ("EPIC-003", "Infrastructure Layer", "EF Core, repositories, cache Redis, jobs Hangfire et migrations.",             "infrastructure"),
    ("EPIC-004", "API Layer",            "Controllers REST et middleware. Expose les services applicatifs.",              "api"),
    ("EPIC-005", "Tests",                "Tests d'intégration Infrastructure (Testcontainers) et tests API end-to-end (WebApplicationFactory). Les tests unitaires Domain et Application sont dans leurs Epics respectifs.", "tests"),
]

# ── Stories ────────────────────────────────────────────────────────────────────

STORIES = [
    # ── Domain (EPIC-001) ────────────────────────────────────────────────────────
    ("STORY-001", "Aggregate Roots",
     "Implémenter les 5 Aggregate Roots du modèle domaine.",
     "Medium", "domain", 5, "EPIC-001"),
    ("STORY-002", "Entités Enfants",
     "Implémenter les entités enfants appartenant à leurs Aggregate Roots.",
     "Medium", "domain", 3, "EPIC-001"),
    ("STORY-003", "Value Objects Domaine",
     "Implémenter les Value Objects immuables du domaine.",
     "Medium", "domain", 3, "EPIC-001"),
    ("STORY-004", "Enums Domaine",
     "Déclarer les enums du modèle domaine.",
     "Medium", "domain", 2, "EPIC-001"),
    ("STORY-005", "Invariants Domaine",
     "Implémenter les règles métier validées dans les constructeurs.",
     "High", "domain", 5, "EPIC-001"),
    ("STORY-028", "Abonnements & Templates — Domaine",
     "Ajouter SubscriptionTier sur User, IsTemplate + UserId nullable sur DietPlan, enum SubscriptionTier.",
     "High", "domain", 3, "EPIC-001"),

    # ── Application (EPIC-002) ───────────────────────────────────────────────────
    ("STORY-006", "UserService",
     "Service applicatif pour la gestion du profil utilisateur et du suivi de poids.",
     "Medium", "application", 3, "EPIC-002"),
    ("STORY-007", "DietPlanService",
     "Service applicatif pour la gestion des plans alimentaires réutilisables.",
     "Medium", "application", 3, "EPIC-002"),
    ("STORY-008", "DietService",
     "Service applicatif pour le cycle de vie des régimes et le calcul nutritionnel au lancement.",
     "High", "application", 8, "EPIC-002"),
    ("STORY-009", "MealService",
     "Service applicatif pour la création et la gestion des repas.",
     "Medium", "application", 3, "EPIC-002"),
    ("STORY-010", "FoodItemService",
     "Service applicatif pour la recherche et la liste personnelle d'aliments.",
     "Medium", "application", 3, "EPIC-002"),
    ("STORY-011", "NutritionService",
     "Service applicatif pour le calcul du bilan nutritionnel d'une période de régime.",
     "High", "application", 5, "EPIC-002"),
    ("STORY-012", "DTOs Application",
     "Définir les objets de transfert de données Request et Response par use case.",
     "Medium", "application", 3, "EPIC-002"),
    ("STORY-029", "SubscriptionGuard — Vérifications tier",
     "Helper centralisé + vérifications de limites par tier dans DietPlanService, MealService, FoodItemService et NutritionService.",
     "High", "application", 5, "EPIC-002"),
    ("STORY-033", "AdminService — KPIs & métriques système",
     "Service applicatif qui agrège les données pour le back-office admin : KPIs utilisateurs, métriques activité, santé des jobs Hangfire.",
     "Medium", "application", 3, "EPIC-002"),

    # ── Infrastructure (EPIC-003) ────────────────────────────────────────────────
    ("STORY-013", "EF Core Configurations",
     "Configurer le mapping objet-relationnel via Fluent API pour chaque entité.",
     "Medium", "infrastructure", 5, "EPIC-003"),
    ("STORY-014", "Repositories",
     "Implémenter les interfaces et repositories EF Core pour chaque Aggregate Root.",
     "Medium", "infrastructure", 5, "EPIC-003"),
    ("STORY-015", "Cache Redis",
     "Configurer et implémenter le cache Redis pour la recherche d'aliments.",
     "Medium", "infrastructure", 3, "EPIC-003"),
    ("STORY-016", "Job Import Open Food Facts",
     "Job Hangfire quotidien d'import du dump Open Food Facts dans la table FoodItem.",
     "High", "infrastructure", 13, "EPIC-003"),
    ("STORY-017", "Job Purge RGPD",
     "Job Hangfire quotidien de suppression définitive des comptes après la grace period de 30 jours.",
     "High", "infrastructure", 8, "EPIC-003"),
    ("STORY-018", "Migrations Base de Données",
     "Créer les migrations EF Core et préparer le jeu de données initial.",
     "Medium", "infrastructure", 2, "EPIC-003"),
    ("STORY-030", "Abonnements & Templates — Infrastructure",
     "Mise à jour DietPlanConfiguration EF Core (IsTemplate, UserId nullable, index) et seed des templates initiaux.",
     "Medium", "infrastructure", 3, "EPIC-003"),
    ("STORY-036", "Configuration Hangfire",
     "Configurer Hangfire avec stockage PostgreSQL, sécuriser le dashboard /hangfire (rôle admin) et enregistrer les jobs récurrents au démarrage.",
     "High", "infrastructure", 3, "EPIC-003"),

    # ── API (EPIC-004) ───────────────────────────────────────────────────────────
    ("STORY-019", "UsersController",
     "Endpoints REST de gestion du profil utilisateur et de conformité RGPD.",
     "High", "api", 8, "EPIC-004"),
    ("STORY-020", "DietPlansController",
     "Endpoints REST de gestion des plans alimentaires réutilisables.",
     "Medium", "api", 5, "EPIC-004"),
    ("STORY-021", "DietsController",
     "Endpoints REST de gestion du cycle de vie des régimes et du bilan nutritionnel.",
     "Medium", "api", 5, "EPIC-004"),
    ("STORY-022", "MealsController",
     "Endpoints REST de création et de gestion des repas et des items de repas.",
     "Medium", "api", 5, "EPIC-004"),
    ("STORY-023", "FoodItemsController",
     "Endpoint REST de recherche d'aliments par mot-clé via cache Redis et PostgreSQL.",
     "Medium", "api", 1, "EPIC-004"),
    ("STORY-024", "Middleware HTTP",
     "Middleware transverses pour l'authentification JWT et la gestion des erreurs.",
     "High", "api", 3, "EPIC-004"),
    ("STORY-031", "Auth & Templates — Nouveaux endpoints",
     "Endpoints GET /diet-plans/templates, POST et PUT /admin/diet-plans/templates. Extraction KeycloakId depuis sub JWT. Réponses 403 par tier.",
     "High", "api", 5, "EPIC-004"),
    ("STORY-034", "AdminController — Dashboard & Santé système",
     "Endpoints GET /admin/dashboard et GET /admin/system/health. Rôle admin requis. Données agrégées uniquement — aucune donnée individuelle.",
     "Medium", "api", 3, "EPIC-004"),
    ("STORY-037", "OpenAPI / Swagger UI",
     "Configurer Swashbuckle : spec OpenAPI 3.0, Swagger UI avec auth JWT Bearer, commentaires XML, désactivé en production.",
     "Medium", "api", 2, "EPIC-004"),

    # ── Tests (EPIC-005) ─────────────────────────────────────────────────────────
    ("STORY-025", "Tests Unitaires Domain",
     "Tests xUnit sur les invariants et règles métier de la couche Domain. Écrits en TDD avant chaque implémentation.",
     "High", "tests", 5, "EPIC-001"),
    ("STORY-038", "Tests Unitaires Application",
     "Tests xUnit avec Moq sur les use cases et règles d'erreur de la couche Application. Écrits en TDD avant chaque implémentation.",
     "High", "tests", 5, "EPIC-002"),
    ("STORY-026", "Tests Intégration Infrastructure",
     "Tests Testcontainers sur les repositories et jobs Hangfire avec PostgreSQL et Redis réels.",
     "Medium", "tests", 8, "EPIC-005"),
    ("STORY-027", "Tests API Endpoints",
     "Tests end-to-end sur tous les endpoints REST avec validation des réponses.",
     "Medium", "tests", 8, "EPIC-005"),
    ("STORY-032", "Tests — Abonnements & Templates",
     "Couvrir les blocages par tier (création plan, accès templates, période bilan, SavedFoodItems).",
     "Medium", "tests", 3, "EPIC-005"),
    ("STORY-035", "Tests — Admin back-office",
     "Tests des endpoints admin : données agrégées correctes, 403 si rôle absent.",
     "Medium", "tests", 2, "EPIC-005"),
]

# ── Sub-tasks ──────────────────────────────────────────────────────────────────

SUBTASKS = [
    # ── STORY-001 : Aggregate Roots ─────────────────────────────────────────────
    ("SUB-001", "Implémenter entité User",
     "Aggregate Root User avec KeycloakId, SubscriptionTier et attributs profil utilisateur.",
     "Medium", "domain", "STORY-001"),
    ("SUB-002", "Implémenter entité DietPlan",
     "Aggregate Root DietPlan — moule de régime réutilisable. IsTemplate (bool) + UserId nullable pour les templates partagés.",
     "Medium", "domain", "STORY-001"),
    ("SUB-003", "Implémenter entité Diet",
     "Aggregate Root Diet — snapshot lancé depuis DietPlan avec CalorieTarget calculé.",
     "Medium", "domain", "STORY-001"),
    ("SUB-004", "Implémenter entité Meal",
     "Aggregate Root Meal avec ConsumedAt et collection de MealItems.",
     "Medium", "domain", "STORY-001"),
    ("SUB-005", "Implémenter entité FoodItem",
     "Aggregate Root FoodItem avec valeurs nutritionnelles et liste d'allergènes.",
     "Medium", "domain", "STORY-001"),

    # ── STORY-002 : Entités Enfants ─────────────────────────────────────────────
    ("SUB-006", "Implémenter entité WeightEntry",
     "Entité enfant de User — poids mesuré à une date donnée.",
     "Medium", "domain", "STORY-002"),
    ("SUB-007", "Implémenter entité MealItem",
     "Entité enfant de Meal — aliment consommé avec quantité et snapshot NutritionInfo.",
     "Medium", "domain", "STORY-002"),
    ("SUB-008", "Implémenter entité SavedFoodItem",
     "Entité enfant de User — référence FoodItem dans la liste personnelle.",
     "Medium", "domain", "STORY-002"),

    # ── STORY-003 : Value Objects ───────────────────────────────────────────────
    ("SUB-009", "Implémenter MacroDistribution",
     "Value Object — pourcentages cibles macros. Invariant : somme = 100.",
     "Medium", "domain", "STORY-003"),
    ("SUB-010", "Implémenter NutritionInfo",
     "Value Object — snapshot grammes réels calculés depuis FoodItem × quantité.",
     "Medium", "domain", "STORY-003"),
    ("SUB-011", "Implémenter NutritionNeeds",
     "Value Object non persisté — Bmr + Tdee + TargetCalories calculés à la demande.",
     "Medium", "domain", "STORY-003"),

    # ── STORY-004 : Enums ───────────────────────────────────────────────────────
    ("SUB-012", "Déclarer enum ActivityLevel",
     "Valeurs : Sedentary, LightlyActive, ModeratelyActive, VeryActive, ExtremelyActive.",
     "Medium", "domain", "STORY-004"),
    ("SUB-013", "Déclarer enum Goal",
     "Valeurs : WeightLoss, Maintenance, WeightGain.",
     "Medium", "domain", "STORY-004"),
    ("SUB-014", "Déclarer enum MealType",
     "Valeurs : Breakfast, Lunch, Dinner, Snack.",
     "Medium", "domain", "STORY-004"),
    ("SUB-015", "Déclarer enum DietType",
     "Valeurs : Balanced, HighProtein, Keto, Mediterranean, LowCarb, Vegetarian, Vegan, Custom.",
     "Medium", "domain", "STORY-004"),
    ("SUB-016", "Déclarer enum DietStatus",
     "Valeurs : Active, Inactive, Archived.",
     "Medium", "domain", "STORY-004"),
    ("SUB-017", "Déclarer enum Gender",
     "Valeurs : Male, Female, Other.",
     "Medium", "domain", "STORY-004"),
    ("SUB-018", "Déclarer enum Allergen",
     "14 valeurs EU : Gluten, Crustaceans, Eggs, Fish, Peanuts, Soybeans, Milk, Nuts, Celery, Mustard, SesameSeeds, SulphurDioxide, Lupin, Molluscs.",
     "Medium", "domain", "STORY-004"),

    # ── STORY-005 : Invariants ──────────────────────────────────────────────────
    ("SUB-019", "Bloquer lancement si Diet active existe déjà",
     "Lever DomainException 409 si l'utilisateur possède déjà une Diet au statut Active.",
     "High", "domain", "STORY-005"),
    ("SUB-020", "Valider présence d'au moins un MealItem",
     "Lever DomainException si Items est vide à la création d'un Meal.",
     "Medium", "domain", "STORY-005"),
    ("SUB-021", "Interdire doublon SavedFoodItem pour un User",
     "Lever DomainException 409 si FoodItemId déjà sauvegardé pour ce User.",
     "Medium", "domain", "STORY-005"),
    ("SUB-022", "Imposer Diet.StartDate à la date du lancement",
     "StartDate assignée par le système au lancement — non modifiable par le client.",
     "High", "domain", "STORY-005"),
    ("SUB-023", "Interdire modification Diet après lancement",
     "Seul EndDate est modifiable sur une Diet lancée.",
     "High", "domain", "STORY-005"),

    # ── STORY-006 : UserService ─────────────────────────────────────────────────
    ("SUB-024", "Créer profil utilisateur avec première WeightEntry",
     "Créer User (SubscriptionTier=Free) et première WeightEntry à la première connexion Keycloak.",
     "Medium", "application", "STORY-006"),
    ("SUB-025", "Mettre à jour profil utilisateur",
     "Mettre à jour les attributs modifiables de User via UserService.",
     "Medium", "application", "STORY-006"),
    ("SUB-026", "Ajouter WeightEntry utilisateur",
     "Ajouter une pesée datée. Rejeter doublon sur même date avec code 409.",
     "Medium", "application", "STORY-006"),

    # ── STORY-007 : DietPlanService ─────────────────────────────────────────────
    ("SUB-027", "Créer un DietPlan",
     "Créer un plan alimentaire réutilisable sans CalorieTarget ni dates.",
     "Medium", "application", "STORY-007"),
    ("SUB-028", "Modifier un DietPlan",
     "Modifier les attributs d'un DietPlan existant appartenant à l'utilisateur.",
     "Medium", "application", "STORY-007"),
    ("SUB-029", "Supprimer un DietPlan",
     "Supprimer un DietPlan appartenant à l'utilisateur courant.",
     "Medium", "application", "STORY-007"),
    ("SUB-030", "Lister les DietPlans d'un utilisateur",
     "Retourner tous les DietPlans de l'utilisateur courant.",
     "Medium", "application", "STORY-007"),

    # ── STORY-008 : DietService ─────────────────────────────────────────────────
    ("SUB-031", "Lancer DietPlan et créer Diet active",
     "Snapshot complet DietPlan vers Diet. Bloquer si une Diet active existe déjà.",
     "High", "application", "STORY-008"),
    ("SUB-032", "Calculer BMR TDEE CalorieTarget au lancement",
     "Formule Mifflin-St Jeor. Utiliser le dernier WeightEntry. Retourner 422 si absent.",
     "High", "application", "STORY-008"),
    ("SUB-033", "Terminer une Diet active",
     "Passer Diet en statut Archived et renseigner EndDate avec la date du jour.",
     "Medium", "application", "STORY-008"),
    ("SUB-034", "Déduire Diet active à la date d'un Meal",
     "Retrouver la Diet dont StartDate <= date du Meal et EndDate nulle ou supérieure.",
     "Medium", "application", "STORY-008"),

    # ── STORY-009 : MealService ─────────────────────────────────────────────────
    ("SUB-035", "Créer Meal avec calcul NutritionInfo",
     "Créer Meal et calculer NutritionInfo pour chaque MealItem depuis FoodItem et quantité.",
     "Medium", "application", "STORY-009"),
    ("SUB-036", "Lister repas sauvegardés",
     "Retourner les Meals de l'utilisateur avec IsSaved égal à true.",
     "Medium", "application", "STORY-009"),
    ("SUB-037", "Supprimer un Meal",
     "Supprimer un Meal et ses MealItems en cascade.",
     "Medium", "application", "STORY-009"),

    # ── STORY-010 : FoodItemService ─────────────────────────────────────────────
    ("SUB-038", "Rechercher aliment par mot-clé",
     "Requête Redis d'abord. Si absent, requête PostgreSQL FoodItem.",
     "Medium", "application", "STORY-010"),
    ("SUB-039", "Sauvegarder FoodItem dans liste personnelle",
     "Créer SavedFoodItem. Rejeter doublon FoodItemId pour cet utilisateur (409).",
     "Medium", "application", "STORY-010"),
    ("SUB-040", "Supprimer SavedFoodItem de la liste personnelle",
     "Supprimer un SavedFoodItem appartenant à l'utilisateur courant.",
     "Medium", "application", "STORY-010"),
    ("SUB-041", "Lister SavedFoodItems d'un utilisateur",
     "Retourner tous les SavedFoodItems avec le détail FoodItem associé.",
     "Medium", "application", "STORY-010"),

    # ── STORY-011 : NutritionService ────────────────────────────────────────────
    ("SUB-042", "Calculer bilan nutritionnel d'une Diet",
     "Agréger les MealItems par jour sur Diet.StartDate à EndDate. Inclure WeightEntries.",
     "High", "application", "STORY-011"),

    # ── STORY-012 : DTOs Application ────────────────────────────────────────────
    ("SUB-043", "Créer CreateUserProfileRequest et UserProfileResponse",
     "DTO pour création et lecture du profil utilisateur.",
     "Medium", "application", "STORY-012"),
    ("SUB-044", "Créer CreateDietPlanRequest et DietPlanResponse",
     "DTO pour création et lecture d'un plan alimentaire.",
     "Medium", "application", "STORY-012"),
    ("SUB-045", "Créer LaunchDietPlanRequest et DietResponse",
     "DTO pour lancement d'un plan et lecture de la Diet résultante.",
     "Medium", "application", "STORY-012"),
    ("SUB-046", "Créer CreateMealRequest et MealResponse",
     "DTO pour création et lecture d'un repas avec ses MealItems.",
     "Medium", "application", "STORY-012"),
    ("SUB-047", "Créer FoodItemSearchResponse",
     "DTO pour les résultats de recherche d'aliments.",
     "Medium", "application", "STORY-012"),
    ("SUB-048", "Créer SaveFoodItemRequest",
     "DTO pour la sauvegarde d'un aliment dans la liste personnelle.",
     "Medium", "application", "STORY-012"),
    ("SUB-049", "Créer NutritionBilanResponse",
     "DTO pour le bilan nutritionnel avec données journalières, pesées et résumé global.",
     "Medium", "application", "STORY-012"),

    # ── STORY-013 : EF Core Configurations ─────────────────────────────────────
    ("SUB-050", "Configurer UserConfiguration Fluent API",
     "Mapping EF Core pour User avec clés primaires, SubscriptionTier et relations.",
     "Medium", "infrastructure", "STORY-013"),
    ("SUB-051", "Configurer DietPlanConfiguration Fluent API",
     "Mapping EF Core pour DietPlan avec owned entity MacroDistribution. UserId nullable, IsTemplate mappé, index sur IsTemplate.",
     "Medium", "infrastructure", "STORY-013"),
    ("SUB-052", "Configurer DietConfiguration Fluent API",
     "Mapping EF Core pour Diet avec owned entity MacroDistribution.",
     "Medium", "infrastructure", "STORY-013"),
    ("SUB-053", "Configurer MealConfiguration Fluent API",
     "Mapping EF Core pour Meal avec cascade delete sur MealItems.",
     "Medium", "infrastructure", "STORY-013"),
    ("SUB-054", "Configurer MealItemConfiguration Fluent API",
     "Mapping EF Core pour MealItem avec owned entity NutritionInfo.",
     "Medium", "infrastructure", "STORY-013"),
    ("SUB-055", "Configurer FoodItemConfiguration Fluent API",
     "Mapping EF Core pour FoodItem avec conversion de la liste Allergen.",
     "Medium", "infrastructure", "STORY-013"),
    ("SUB-056", "Configurer WeightEntryConfiguration Fluent API",
     "Mapping EF Core pour WeightEntry avec contrainte unique UserId + MeasuredAt.",
     "Medium", "infrastructure", "STORY-013"),
    ("SUB-057", "Configurer SavedFoodItemConfiguration Fluent API",
     "Mapping EF Core pour SavedFoodItem avec contrainte unique UserId + FoodItemId.",
     "Medium", "infrastructure", "STORY-013"),
    ("SUB-058", "Configurer MacroDistribution en owned entity EF Core",
     "Mapping Fluent API : CarbsPercent, ProteinsPercent, FatsPercent.",
     "Medium", "infrastructure", "STORY-013"),
    ("SUB-059", "Configurer NutritionInfo en owned entity EF Core",
     "Mapping Fluent API : Calories, Proteins, Carbs, Fats.",
     "Medium", "infrastructure", "STORY-013"),

    # ── STORY-014 : Repositories ────────────────────────────────────────────────
    ("SUB-060", "Implémenter IUserRepository et UserRepository",
     "Interface Application et implémentation EF Core pour User.",
     "Medium", "infrastructure", "STORY-014"),
    ("SUB-061", "Implémenter IDietPlanRepository et DietPlanRepository",
     "Interface Application et implémentation EF Core pour DietPlan.",
     "Medium", "infrastructure", "STORY-014"),
    ("SUB-062", "Implémenter IDietRepository et DietRepository",
     "Interface Application et implémentation EF Core pour Diet.",
     "Medium", "infrastructure", "STORY-014"),
    ("SUB-063", "Implémenter IMealRepository et MealRepository",
     "Interface Application et implémentation EF Core pour Meal.",
     "Medium", "infrastructure", "STORY-014"),
    ("SUB-064", "Implémenter IFoodItemRepository et FoodItemRepository",
     "Interface Application et implémentation EF Core pour FoodItem.",
     "Medium", "infrastructure", "STORY-014"),
    ("SUB-065", "Implémenter IWeightEntryRepository et WeightEntryRepository",
     "Interface Application et implémentation EF Core pour WeightEntry.",
     "Medium", "infrastructure", "STORY-014"),
    ("SUB-066", "Implémenter ISavedFoodItemRepository et SavedFoodItemRepository",
     "Interface Application et implémentation EF Core pour SavedFoodItem.",
     "Medium", "infrastructure", "STORY-014"),

    # ── STORY-015 : Cache Redis ──────────────────────────────────────────────────
    ("SUB-067", "Configurer IConnectionMultiplexer Redis",
     "Enregistrer IConnectionMultiplexer dans le conteneur DI.",
     "Medium", "infrastructure", "STORY-015"),
    ("SUB-068", "Implémenter IFoodCacheService et FoodCacheService",
     "Service de cache get et set par mot-clé avec TTL configurable.",
     "Medium", "infrastructure", "STORY-015"),

    # ── STORY-016 : Job Import OFF (Hangfire) ───────────────────────────────────
    ("SUB-069", "Télécharger le dump Open Food Facts",
     "Télécharger le fichier JSONL ou CSV depuis les serveurs Open Food Facts.",
     "High", "infrastructure", "STORY-016"),
    ("SUB-070", "Traiter le dump par batch INSERT UPDATE FoodItem",
     "Parcourir le dump et exécuter INSERT ou UPDATE sur FoodItem par lots.",
     "High", "infrastructure", "STORY-016"),
    ("SUB-071", "Implémenter IOffImportJob et OffImportJob",
     "Classe job Hangfire dans Infrastructure/Jobs/ — implémente l'interface pour la résolution DI.",
     "Medium", "infrastructure", "STORY-016"),
    ("SUB-072", "Gérer erreurs import et reprise après échec",
     "Logger les erreurs par lot. Hangfire gère le retry automatique selon la politique configurée.",
     "Medium", "infrastructure", "STORY-016"),

    # ── STORY-017 : Job Purge RGPD (Hangfire) ──────────────────────────────────
    ("SUB-073", "Sélectionner comptes à purger après 30 jours",
     "Requête Users dont DeletedAt <= aujourd'hui - 30 jours.",
     "High", "infrastructure", "STORY-017"),
    ("SUB-074", "Supprimer données utilisateur en cascade PostgreSQL",
     "Cascade DELETE : MealItems → Meals → WeightEntries → SavedFoodItems → DietPlans → Diets → User.",
     "High", "infrastructure", "STORY-017"),
    ("SUB-075", "Supprimer utilisateur dans Keycloak Admin",
     "Appeler l'API Keycloak Admin pour supprimer par KeycloakId.",
     "High", "infrastructure", "STORY-017"),
    ("SUB-076", "Implémenter IRgpdPurgeJob et RgpdPurgeJob",
     "Classe job Hangfire dans Infrastructure/Jobs/ — implémente l'interface pour la résolution DI.",
     "High", "infrastructure", "STORY-017"),
    ("SUB-077", "Gérer erreurs Keycloak indisponible avec retry Polly",
     "Retry Polly si Keycloak indisponible. Ignorer si utilisateur déjà absent.",
     "High", "infrastructure", "STORY-017"),

    # ── STORY-018 : Migrations ───────────────────────────────────────────────────
    ("SUB-078", "Créer migration initiale EF Core",
     "Générer la migration EF Core initiale depuis le DbContext configuré.",
     "Medium", "infrastructure", "STORY-018"),
    ("SUB-079", "Préparer import initial dump Open Food Facts",
     "Script ou seed exécuté au premier déploiement pour peupler FoodItem.",
     "Medium", "infrastructure", "STORY-018"),

    # ── STORY-019 : UsersController ─────────────────────────────────────────────
    ("SUB-080", "Implémenter POST /users/me",
     "Créer le profil utilisateur depuis le token Keycloak à la première connexion.",
     "Medium", "api", "STORY-019"),
    ("SUB-081", "Implémenter GET /users/me",
     "Lire le profil utilisateur avec BMR et TDEE calculés à la demande.",
     "Medium", "api", "STORY-019"),
    ("SUB-082", "Implémenter PUT /users/me",
     "Mettre à jour les attributs modifiables du profil utilisateur.",
     "Medium", "api", "STORY-019"),
    ("SUB-083", "Implémenter POST /users/me/weight-entries",
     "Ajouter une pesée pour l'utilisateur courant.",
     "Medium", "api", "STORY-019"),
    ("SUB-084", "Implémenter GET /users/me/weight-entries",
     "Retourner l'historique des pesées de l'utilisateur courant.",
     "Medium", "api", "STORY-019"),
    ("SUB-085", "Implémenter PUT /users/me/weight-entries/{id}",
     "Modifier une pesée existante de l'utilisateur courant.",
     "Medium", "api", "STORY-019"),
    ("SUB-086", "Implémenter GET /users/me/saved-food-items",
     "Retourner la liste personnelle d'aliments de l'utilisateur courant.",
     "Medium", "api", "STORY-019"),
    ("SUB-087", "Implémenter POST /users/me/saved-food-items",
     "Sauvegarder un aliment dans la liste personnelle.",
     "Medium", "api", "STORY-019"),
    ("SUB-088", "Implémenter DELETE /users/me/saved-food-items/{id}",
     "Retirer un aliment de la liste personnelle.",
     "Medium", "api", "STORY-019"),
    ("SUB-089", "Implémenter DELETE /users/me (suppression RGPD)",
     "Soft delete + désactivation Keycloak. RGPD Art. 17.",
     "High", "api", "STORY-019"),
    ("SUB-090", "Implémenter POST /users/me/reactivate",
     "Réactiver le compte pendant la grace period RGPD.",
     "High", "api", "STORY-019"),
    ("SUB-091", "Implémenter GET /users/me/export (RGPD Art. 20)",
     "Exporter toutes les données personnelles en JSON.",
     "High", "api", "STORY-019"),

    # ── STORY-020 : DietPlansController ─────────────────────────────────────────
    ("SUB-092", "Implémenter POST /diet-plans",
     "Créer un nouveau plan alimentaire réutilisable.",
     "Medium", "api", "STORY-020"),
    ("SUB-093", "Implémenter GET /diet-plans",
     "Lister tous les plans alimentaires de l'utilisateur courant.",
     "Medium", "api", "STORY-020"),
    ("SUB-094", "Implémenter PUT /diet-plans/{id}",
     "Modifier un plan alimentaire existant.",
     "Medium", "api", "STORY-020"),
    ("SUB-095", "Implémenter DELETE /diet-plans/{id}",
     "Supprimer un plan alimentaire de l'utilisateur courant.",
     "Medium", "api", "STORY-020"),
    ("SUB-096", "Implémenter POST /diet-plans/{id}/launch",
     "Lancer un plan et créer une Diet active avec CalorieTarget calculé.",
     "High", "api", "STORY-020"),

    # ── STORY-021 : DietsController ─────────────────────────────────────────────
    ("SUB-097", "Implémenter GET /diets/active",
     "Retourner le régime actif de l'utilisateur courant.",
     "Medium", "api", "STORY-021"),
    ("SUB-098", "Implémenter GET /diets (historique)",
     "Lister tous les régimes de l'utilisateur courant avec leur statut.",
     "Medium", "api", "STORY-021"),
    ("SUB-099", "Implémenter GET /diets/{id}",
     "Retourner le détail d'un régime spécifique.",
     "Medium", "api", "STORY-021"),
    ("SUB-100", "Implémenter POST /diets/{id}/archive",
     "Terminer un régime actif et passer son statut à Archived.",
     "Medium", "api", "STORY-021"),
    ("SUB-101", "Implémenter GET /diets/{id}/bilan",
     "Calculer et retourner le bilan nutritionnel d'un régime sur sa période.",
     "High", "api", "STORY-021"),

    # ── STORY-022 : MealsController ─────────────────────────────────────────────
    ("SUB-102", "Implémenter POST /meals",
     "Créer un repas avec calcul NutritionInfo par MealItem.",
     "Medium", "api", "STORY-022"),
    ("SUB-103", "Implémenter GET /meals",
     "Lister les repas de l'utilisateur avec filtres par date et par statut sauvegardé.",
     "Medium", "api", "STORY-022"),
    ("SUB-104", "Implémenter GET /meals/{id}",
     "Retourner le détail d'un repas avec ses MealItems.",
     "Medium", "api", "STORY-022"),
    ("SUB-105", "Implémenter DELETE /meals/{id}",
     "Supprimer un repas et ses MealItems en cascade.",
     "Medium", "api", "STORY-022"),
    ("SUB-106", "Implémenter POST /meals/{id}/items",
     "Ajouter un MealItem à un repas existant.",
     "Medium", "api", "STORY-022"),
    ("SUB-107", "Implémenter DELETE /meals/{id}/items/{itemId}",
     "Retirer un MealItem spécifique d'un repas existant.",
     "Medium", "api", "STORY-022"),

    # ── STORY-023 : FoodItemsController ─────────────────────────────────────────
    ("SUB-108", "Implémenter GET /food-items (recherche par mot-clé)",
     "Rechercher des aliments par mot-clé via cache Redis puis base PostgreSQL.",
     "Medium", "api", "STORY-023"),

    # ── STORY-024 : Middleware HTTP ──────────────────────────────────────────────
    ("SUB-109", "Implémenter validation JWT Keycloak",
     "Middleware d'authentification qui valide le token JWT émis par Keycloak.",
     "High", "api", "STORY-024"),
    ("SUB-110", "Implémenter gestion globale des erreurs HTTP",
     "Middleware exception qui convertit les DomainException en codes HTTP.",
     "High", "api", "STORY-024"),
    ("SUB-111", "Implémenter logging des requêtes entrantes",
     "Middleware de logging structuré pour chaque requête et réponse HTTP.",
     "Medium", "api", "STORY-024"),

    # ── STORY-025 : Tests Unitaires Domain ───────────────────────────────────────
    ("SUB-112", "Tester MacroDistribution invariant somme 100%",
     "Vérifier que la construction échoue si la somme des pourcentages ≠ 100.",
     "High", "tests", "STORY-025"),
    ("SUB-113", "Tester NutritionInfo calcul snapshot correct",
     "Vérifier les valeurs nutritionnelles calculées depuis FoodItem et quantité.",
     "Medium", "tests", "STORY-025"),
    ("SUB-114", "Tester Diet règle unicité régime actif",
     "Vérifier que le lancement lève une DomainException si une Diet Active existe déjà pour cet utilisateur.",
     "High", "tests", "STORY-025"),
    ("SUB-158", "Tester Meal — DomainException si aucun MealItem à la création",
     "Vérifier que la construction d'un Meal sans Items lève une DomainException.",
     "High", "tests", "STORY-025"),
    ("SUB-159", "Tester SavedFoodItem — doublon interdit par User",
     "Vérifier que sauvegarder deux fois le même FoodItemId pour un même User lève une DomainException.",
     "Medium", "tests", "STORY-025"),
    ("SUB-160", "Tester Diet — StartDate imposée système non modifiable",
     "Vérifier que StartDate est assignée par le système au lancement et ne peut pas être fournie par le client.",
     "High", "tests", "STORY-025"),
    ("SUB-161", "Tester Diet — immutabilité après lancement sauf EndDate",
     "Vérifier que toute modification d'une Diet lancée hors EndDate lève une DomainException.",
     "High", "tests", "STORY-025"),
    ("SUB-162", "Tester WeightEntry — doublon même date même User",
     "Vérifier qu'une deuxième WeightEntry sur la même date pour le même User lève une DomainException.",
     "Medium", "tests", "STORY-025"),

    # ── STORY-038 : Tests Unitaires Application ──────────────────────────────────
    ("SUB-163", "Tester UserService — WeightEntry doublon même date → 409",
     "Moq IWeightEntryRepository. Vérifier que le service retourne 409 si une entrée existe déjà à cette date.",
     "Medium", "tests", "STORY-038"),
    ("SUB-164", "Tester DietService — lancement sans WeightEntry → 422",
     "Moq IWeightEntryRepository retournant null. Vérifier que le service lève une exception 422.",
     "High", "tests", "STORY-038"),
    ("SUB-165", "Tester DietService — lancement avec Diet active existante → 409",
     "Moq IDietRepository retournant une Diet Active. Vérifier que le service retourne 409.",
     "High", "tests", "STORY-038"),
    ("SUB-166", "Tester MealService — création Meal sans MealItem → rejeté",
     "Vérifier que le service rejette la création d'un Meal avec une liste Items vide.",
     "High", "tests", "STORY-038"),
    ("SUB-167", "Tester FoodItemService — SavedFoodItem doublon → 409",
     "Moq ISavedFoodItemRepository retournant un existant. Vérifier retour 409.",
     "Medium", "tests", "STORY-038"),
    ("SUB-168", "Tester NutritionService — bilan agrégation journalière correcte",
     "Moq IMealRepository + IWeightEntryRepository. Vérifier que les totaux journaliers sont correctement agrégés.",
     "High", "tests", "STORY-038"),
    ("SUB-169", "Tester SubscriptionGuard — blocage limite plans Free",
     "Moq IDietPlanRepository retournant 2 plans. Vérifier retour 403 à la tentative de création d'un 3ème.",
     "High", "tests", "STORY-038"),
    ("SUB-170", "Tester SubscriptionGuard — blocage repas sauvegardé Free",
     "Moq IMealRepository retournant 5 repas sauvegardés. Vérifier retour 403.",
     "High", "tests", "STORY-038"),
    ("SUB-171", "Tester SubscriptionGuard — restriction période bilan Free 7j",
     "Vérifier que la période effective retournée pour un utilisateur Free est clampée à 7 jours.",
     "High", "tests", "STORY-038"),

    # ── STORY-026 : Tests Intégration ────────────────────────────────────────────
    ("SUB-115", "Tester repositories avec Testcontainers PostgreSQL",
     "Tests d'intégration sur les 7 repositories avec base PostgreSQL réelle.",
     "Medium", "tests", "STORY-026"),
    ("SUB-116", "Tester cache Redis avec Testcontainers",
     "Tests d'intégration sur FoodCacheService avec instance Redis.",
     "Medium", "tests", "STORY-026"),
    ("SUB-117", "Tester job import Open Food Facts avec dump test",
     "Tests d'intégration sur le job Hangfire d'import avec un dump de test réduit.",
     "Medium", "tests", "STORY-026"),

    # ── STORY-027 : Tests API ────────────────────────────────────────────────────
    ("SUB-118", "Tester tous les endpoints cas nominaux et cas erreur",
     "Couvrir chaque endpoint avec au moins un test nominal et les cas 400, 401, 404, 409.",
     "Medium", "tests", "STORY-027"),
    ("SUB-119", "Tester rejet JWT invalide sur endpoints protégés",
     "Vérifier que les endpoints retournent 401 pour tout token absent ou invalide.",
     "High", "tests", "STORY-027"),

    # ── STORY-028 : Domaine Abonnements & Templates ──────────────────────────────
    ("SUB-120", "Déclarer enum SubscriptionTier",
     "Valeurs : Free, Pro, Business.",
     "Medium", "domain", "STORY-028"),
    ("SUB-121", "Ajouter User.SubscriptionTier",
     "Champ SubscriptionTier sur User, valeur par défaut Free à la création.",
     "Medium", "domain", "STORY-028"),
    ("SUB-122", "Ajouter DietPlan.IsTemplate",
     "Bool IsTemplate sur DietPlan. False par défaut (plan personnel). True = template partagé, read-only pour les utilisateurs.",
     "Medium", "domain", "STORY-028"),
    ("SUB-123", "Passer DietPlan.UserId en Guid nullable",
     "UserId devient Guid? — null si IsTemplate = true. Invariant : template sans propriétaire.",
     "Medium", "domain", "STORY-028"),

    # ── STORY-029 : SubscriptionGuard ───────────────────────────────────────────
    ("SUB-124", "Implémenter helper SubscriptionGuard",
     "Méthode centralisée CheckLimit(user, limitType, count) — retourne 403 si limite tier atteinte.",
     "High", "application", "STORY-029"),
    ("SUB-125", "Vérifier limite plans personnels dans DietPlanService",
     "Avant création : compter DietPlan IsTemplate=false de l'utilisateur. Bloquer si Free >= 2 ou Pro >= 20.",
     "High", "application", "STORY-029"),
    ("SUB-126", "Bloquer accès templates si tier Free dans DietPlanService",
     "Retourner 403 si SubscriptionTier = Free sur GET /diet-plans/templates.",
     "High", "application", "STORY-029"),
    ("SUB-127", "Lister les DietPlan templates partagés",
     "Nouvelle méthode dans DietPlanService : retourner tous les DietPlan WHERE IsTemplate = true.",
     "Medium", "application", "STORY-029"),
    ("SUB-128", "Vérifier limite repas sauvegardés dans MealService",
     "Avant IsSaved=true : compter Meals sauvegardés. Bloquer si Free >= 5 ou Pro >= 50.",
     "High", "application", "STORY-029"),
    ("SUB-129", "Vérifier limite SavedFoodItems dans FoodItemService",
     "Avant ajout SavedFoodItem : compter les existants. Bloquer si Free >= 10 ou Pro >= 100.",
     "High", "application", "STORY-029"),
    ("SUB-130", "Restreindre période bilan selon tier dans NutritionService",
     "Clamper la période effective : Free = 7 derniers jours, Pro = 1 an, Business = illimité.",
     "High", "application", "STORY-029"),

    # ── STORY-030 : Infrastructure Abonnements & Templates ──────────────────────
    ("SUB-131", "Mettre à jour DietPlanConfiguration EF Core",
     "UserId nullable, IsTemplate mappé, index sur IsTemplate pour filtrage rapide des templates.",
     "Medium", "infrastructure", "STORY-030"),
    ("SUB-132", "Seed des templates initiaux",
     "Insérer les DietPlan templates de départ (IsTemplate=true, UserId=null) via migration ou fichier JSON de seed.",
     "Medium", "infrastructure", "STORY-030"),

    # ── STORY-031 : Auth & Templates — Nouveaux endpoints ───────────────────────
    ("SUB-133", "Implémenter GET /diet-plans/templates",
     "Retourner tous les templates partagés. Accessible Pro et Business uniquement (403 si Free).",
     "High", "api", "STORY-031"),
    ("SUB-134", "Implémenter POST /admin/diet-plans/templates",
     "Créer un template partagé. Protégé par le rôle admin Keycloak (realm_access.roles).",
     "Medium", "api", "STORY-031"),
    ("SUB-135", "Implémenter PUT /admin/diet-plans/templates/{id}",
     "Modifier un template existant. Protégé par le rôle admin Keycloak.",
     "Medium", "api", "STORY-031"),
    ("SUB-136", "Extraction KeycloakId depuis claim sub dans le middleware JWT",
     "Après validation du token, extraire sub → User.KeycloakId pour résolution interne.",
     "High", "api", "STORY-031"),
    ("SUB-137", "Réponses 403 tier insuffisant avec message explicite",
     "Retourner 403 avec message lisible indiquant le tier requis.",
     "Medium", "api", "STORY-031"),

    # ── STORY-032 : Tests Abonnements & Templates ────────────────────────────────
    ("SUB-138", "Tester blocage création plan si limite Free atteinte",
     "Vérifier retour 403 quand un utilisateur Free tente de créer un 3ème DietPlan personnel.",
     "Medium", "tests", "STORY-032"),
    ("SUB-139", "Tester blocage accès templates pour tier Free",
     "Vérifier retour 403 sur GET /diet-plans/templates pour un utilisateur Free.",
     "Medium", "tests", "STORY-032"),
    ("SUB-140", "Tester restriction période bilan selon tier",
     "Vérifier que la période retournée est clampée à 7j pour Free, 1 an pour Pro, illimitée pour Business.",
     "Medium", "tests", "STORY-032"),
    ("SUB-141", "Tester blocage SavedFoodItem limite Free",
     "Vérifier retour 403 quand un utilisateur Free tente d'ajouter un 11ème SavedFoodItem.",
     "Medium", "tests", "STORY-032"),

    # ── STORY-033 : AdminService ─────────────────────────────────────────────────
    ("SUB-142", "Agréger KPIs utilisateurs",
     "Compter le total d'utilisateurs, la répartition par SubscriptionTier (Free/Pro/Business) et les nouveaux inscrits sur les 7 derniers jours.",
     "Medium", "application", "STORY-033"),
    ("SUB-143", "Agréger métriques activité",
     "Compter les Diets au statut Active, les Meals créés sur les 7 derniers jours, et les Users avec DeletedAt non null (en grace period).",
     "Medium", "application", "STORY-033"),
    ("SUB-144", "Agréger santé système depuis tables Hangfire",
     "Lire la date et le statut du dernier import OFF et du dernier job purge depuis HangFire.Job + HangFire.State. Statuts : success / failed / never_run.",
     "Medium", "application", "STORY-033"),

    # ── STORY-034 : AdminController ──────────────────────────────────────────────
    ("SUB-145", "Implémenter GET /admin/dashboard",
     "Retourner les KPIs consolidés : users (total, par tier, nouveaux 7j) + activity (diets actives, repas 7j, grace period). Rôle admin requis.",
     "Medium", "api", "STORY-034"),
    ("SUB-146", "Implémenter GET /admin/system/health",
     "Retourner le statut des jobs Hangfire (offImport + rgpdPurge) et le count FoodItems. Rôle admin requis.",
     "Medium", "api", "STORY-034"),
    ("SUB-147", "Implémenter DELETE /admin/diet-plans/templates/{id}",
     "Supprimer un DietPlan template (IsTemplate = true). Rôle admin requis. Retourner 404 si introuvable.",
     "Medium", "api", "STORY-034"),

    # ── STORY-035 : Tests Admin ──────────────────────────────────────────────────
    ("SUB-148", "Tester GET /admin/dashboard — données agrégées correctes",
     "Vérifier que les comptes et métriques retournés correspondent aux données en base.",
     "Medium", "tests", "STORY-035"),
    ("SUB-149", "Tester GET /admin/dashboard — 403 si rôle admin absent",
     "Vérifier que l'endpoint retourne 403 pour un token valide sans le rôle admin.",
     "Medium", "tests", "STORY-035"),
    ("SUB-150", "Tester GET /admin/system/health — statuts jobs corrects",
     "Vérifier les statuts success/failed/never_run selon l'état des tables Hangfire.",
     "Medium", "tests", "STORY-035"),

    # ── STORY-037 : OpenAPI / Swagger UI ────────────────────────────────────────
    ("SUB-154", "Configurer AddSwaggerGen avec sécurité JWT Bearer",
     "Enregistrer SwaggerGen dans DI : titre, version, OpenApiSecurityDefinition Bearer, AddSecurityRequirement sur endpoints [Authorize].",
     "Medium", "api", "STORY-037"),
    ("SUB-155", "Activer Swagger UI hors production",
     "app.UseSwagger() + app.UseSwaggerUI() conditionnels — désactivés si app.Environment.IsProduction().",
     "Medium", "api", "STORY-037"),
    ("SUB-156", "Activer commentaires XML sur les projets API et Application",
     "Ajouter <GenerateDocumentationFile>true</GenerateDocumentationFile> dans les .csproj API et Application. Référencer le fichier XML dans IncludeXmlComments.",
     "Medium", "api", "STORY-037"),
    ("SUB-157", "Exclure le dashboard Hangfire de la spec OpenAPI",
     "Configurer un filtre ou une convention pour que /hangfire n'apparaisse pas dans swagger.json.",
     "Low", "api", "STORY-037"),

    # ── STORY-036 : Configuration Hangfire ──────────────────────────────────────
    ("SUB-151", "Configurer Hangfire avec stockage PostgreSQL",
     "Enregistrer Hangfire dans DI avec PostgreSqlStorage (schéma HangFire, PrepareSchemaIfNecessary=true). Voir infrastructure-hangfire.md.",
     "High", "infrastructure", "STORY-036"),
    ("SUB-152", "Sécuriser le dashboard /hangfire — rôle admin Keycloak",
     "Implémenter HangfireAdminAuthorizationFilter : authentifié + claim realm_access_roles = admin.",
     "High", "infrastructure", "STORY-036"),
    ("SUB-153", "Enregistrer les jobs récurrents au démarrage",
     "RecurringJob.AddOrUpdate pour OffImportJob (cron 0 3 * * *) et RgpdPurgeJob (cron 30 3 * * *) dans Program.cs.",
     "High", "infrastructure", "STORY-036"),
]
